version = 1

test_patterns = [
  'tests/**'
]

exclude_patterns = [
  'docs/**',
  'conf/**'
]

[[analyzers]]
name = 'python'
enabled = true
runtime_version = '2.x.x'
  
  [analyzers.meta]
  'max_line_length' = 100
